- name: Copy travis license file to server
  template:
    src: license.rli.j2
    dest: /tmp/license.rli
    owner: root
    group: root
    mode: 0644

- name: Create a travis settings file
  template:
    src: settings.json.j2
    dest: /tmp/settings.json
    owner: root
    group: root
    mode: 0644

- name: Write the replicated.conf
  template:
    src: replicated.conf.j2
    dest: /etc/replicated.conf
    owner: root
    group: root
    mode: 0644
