---
# Replicated Ansible Variables

replicated_version: "2.0"             # This can be 1.2 or 2.0
replicated_channel: stable          # stable | beta | unstable
replicated_environment: production  # production | staging

docker_pkg_name: lxc-docker-1.9.1
docker_kernel_pkg_state: latest
docker_apt_key_url: https://get.docker.com/gpg
docker_apt_key_sig: A88D21E9
docker_apt_repository: deb https://get.docker.com/ubuntu docker main

replicated_image_tag: "latest"
